"""
Supabase Migrator Module.

Main migration script that orchestrates the migration process.
"""

import logging
from typing import Dict, Any, Optional, List
from pathlib import Path
import pandas as pd

from supabase import create_client, Client
from supabase_migration.config import SupabaseConfig
from supabase_migration.transformers import (
    transform_ccyb_data,
    transform_syrb_data,
    transform_bbm_data,
    transform_osii_data,
    transform_dti_lti_data,
    transform_ltv_data,
    transform_countries,
    transform_snapshots,
    transform_trends,
)
from supabase_migration.validators import validate_data_before_migration
from config import FILES, DATA_DIR

logger = logging.getLogger(__name__)


class SupabaseMigrator:
    """Main migrator class for Supabase migration."""
    
    def __init__(self, config: Optional[SupabaseConfig] = None, use_service_key: bool = False):
        """
        Initialize migrator.
        
        Args:
            config: SupabaseConfig instance (if None, creates new one)
            use_service_key: If True, use service role key (bypasses RLS). If False, use anon key.
        """
        self.config = config or SupabaseConfig()
        
        if not self.config.is_configured():
            raise ValueError("Supabase is not properly configured. Check environment variables.")
        
        # Use service key if available and requested (bypasses RLS)
        if use_service_key and self.config.service_key:
            key = self.config.service_key
            logger.info("Using service role key (bypasses RLS)")
        else:
            key = self.config.anon_key
            if use_service_key:
                logger.warning("Service key requested but not configured. Using anon key (may fail with RLS).")
        
        self.client: Client = create_client(self.config.url, key)
        logger.info(f"Initialized Supabase migrator: {self.config}")
    
    def migrate_all(
        self,
        data_dir: Optional[Path] = None,
        validate: bool = True,
        dry_run: bool = False,
    ) -> Dict[str, Any]:
        """
        Migrate all data to Supabase.
        
        Args:
            data_dir: Directory containing parquet files (default: config.DATA_DIR)
            validate: Whether to validate data before migration
            dry_run: If True, only validate and transform, don't insert
            
        Returns:
            Dictionary with migration results
        """
        data_dir = data_dir or DATA_DIR
        
        logger.info("=" * 60)
        logger.info("Starting Supabase Migration")
        logger.info("=" * 60)
        
        # Load data
        logger.info("\n1. Loading data from Parquet files...")
        ccyb_df = pd.read_parquet(FILES["ccyb_processed"]) if FILES["ccyb_processed"].exists() else pd.DataFrame()
        syrb_df = pd.read_parquet(FILES["syrb_processed"]) if FILES["syrb_processed"].exists() else pd.DataFrame()
        bbm_df = pd.read_parquet(FILES["bbm_processed"]) if FILES["bbm_processed"].exists() else pd.DataFrame()
        osii_df = pd.read_parquet(FILES["osii_processed"]) if FILES["osii_processed"].exists() else pd.DataFrame()
        latest_ccyb = pd.read_parquet(FILES["latest_ccyb"]) if FILES["latest_ccyb"].exists() else pd.DataFrame()
        latest_syrb = pd.read_parquet(FILES["latest_syrb"]) if FILES["latest_syrb"].exists() else pd.DataFrame()
        latest_osii = pd.read_parquet(FILES["latest_osii"]) if FILES["latest_osii"].exists() else pd.DataFrame()
        
        # Load DTI/LTI CSV
        dti_lti_csv = DATA_DIR / "dti_lti_rules.csv"
        dti_lti_df = pd.read_csv(dti_lti_csv) if dti_lti_csv.exists() else pd.DataFrame()
        
        # Load LTV data (if exists as CSV, otherwise will be generated by pipeline)
        ltv_csv = DATA_DIR / "ltv_rules.csv"
        ltv_df = pd.read_csv(ltv_csv) if ltv_csv.exists() else pd.DataFrame()
        
        # Load trend data
        agg_trend = pd.read_parquet(DATA_DIR / "agg_trend.parquet") if (DATA_DIR / "agg_trend.parquet").exists() else pd.DataFrame()
        syrb_trend = pd.DataFrame()  # Not saved separately, will calculate from syrb_df
        bbm_trend = pd.DataFrame()  # Not saved separately, will calculate from bbm_df
        
        logger.info(f"   Loaded: CCyB={len(ccyb_df)}, SyRB={len(syrb_df)}, BBM={len(bbm_df)}, OSII={len(osii_df)}")
        logger.info(f"   DTI/LTI={len(dti_lti_df)}, LTV={len(ltv_df)}")
        logger.info(f"   Trends: CCyB={len(agg_trend)}")
        
        # Transform data
        logger.info("\n2. Transforming data to Supabase format...")
        countries_records = transform_countries(ccyb_df, syrb_df, bbm_df, osii_df)
        ccyb_records = transform_ccyb_data(ccyb_df)
        syrb_records = transform_syrb_data(syrb_df)
        bbm_records = transform_bbm_data(bbm_df)
        osii_records = transform_osii_data(osii_df)
        dti_lti_records = transform_dti_lti_data(dti_lti_df)
        ltv_records = transform_ltv_data(ltv_df)
        snapshots = transform_snapshots(latest_ccyb, latest_syrb, latest_osii)
        trends = transform_trends(agg_trend, syrb_trend, bbm_trend, ccyb_df, syrb_df, bbm_df)
        
        # Validate data
        if validate:
            logger.info("\n3. Validating data...")
            is_valid, errors = validate_data_before_migration(
                ccyb_records, syrb_records, bbm_records, osii_records,
                dti_lti_records, ltv_records, countries_records
            )
            
            if not is_valid:
                logger.error(f"Validation failed with {len(errors)} errors!")
                if not dry_run:
                    raise ValueError(f"Data validation failed. Found {len(errors)} errors.")
        
        # Migrate to Supabase
        if dry_run:
            logger.info("\n4. DRY RUN - Skipping database insertion")
            return {
                "status": "dry_run",
                "countries": len(countries_records),
                "ccyb": len(ccyb_records),
                "syrb": len(syrb_records),
                "bbm": len(bbm_records),
                "osii": len(osii_records),
                "dti_lti": len(dti_lti_records),
                "ltv": len(ltv_records),
            }
        
        logger.info("\n4. Migrating to Supabase...")
        results = {}
        
        try:
            # 1. Countries (must be first due to foreign keys)
            logger.info("   -> Migrating countries...")
            if countries_records:
                self.client.table("countries").upsert(countries_records).execute()
                results["countries"] = len(countries_records)
            
            # 2. CCyB Decisions (remove duplicates based on unique constraint)
            logger.info("   -> Migrating CCyB decisions...")
            if ccyb_records:
                # Remove duplicates based on (country_iso2, effective_date)
                seen = set()
                unique_records = []
                for record in ccyb_records:
                    key = (record.get("country_iso2"), record.get("effective_date"))
                    if key not in seen:
                        seen.add(key)
                        unique_records.append(record)
                
                if len(unique_records) < len(ccyb_records):
                    logger.info(f"   -> Removed {len(ccyb_records) - len(unique_records)} duplicate CCyB records")
                
                # Upsert with conflict resolution on (country_iso2, effective_date)
                self.client.table("ccyb_decisions").upsert(
                    unique_records,
                    on_conflict="country_iso2,effective_date"
                ).execute()
                results["ccyb"] = len(unique_records)
            
            # 3. SyRB Measures
            logger.info("   -> Migrating SyRB measures...")
            if syrb_records:
                # SyRB doesn't have a unique constraint, so we can just insert
                # But we'll use upsert anyway to handle potential duplicates
                self.client.table("syrb_measures").upsert(syrb_records).execute()
                results["syrb"] = len(syrb_records)
            
            # 4. BBM Measures
            logger.info("   -> Migrating BBM measures...")
            if bbm_records:
                self.client.table("bbm_measures").upsert(bbm_records).execute()
                results["bbm"] = len(bbm_records)
            
            # 5. DTI/LTI Rules
            logger.info("   -> Migrating DTI/LTI rules...")
            if dti_lti_records:
                # Upsert with conflict resolution on (country_iso2, measure_code)
                self.client.table("dti_lti_rules").upsert(
                    dti_lti_records,
                    on_conflict="country_iso2,measure_code"
                ).execute()
                results["dti_lti"] = len(dti_lti_records)
            
            # 6. LTV Rules
            logger.info("   -> Migrating LTV rules...")
            if ltv_records:
                # Upsert with conflict resolution on country_iso2
                self.client.table("ltv_rules").upsert(
                    ltv_records,
                    on_conflict="country_iso2"
                ).execute()
                results["ltv"] = len(ltv_records)
            
            # 7. OSII Banks
            logger.info("   -> Migrating OSII banks...")
            if osii_records:
                self.client.table("osii_banks").upsert(osii_records).execute()
                results["osii"] = len(osii_records)
            
            # 8. Snapshots (remove duplicates based on country_iso2)
            logger.info("   -> Migrating snapshots...")
            if snapshots["ccyb"]:
                # Remove duplicates
                seen = set()
                unique_ccyb = []
                for record in snapshots["ccyb"]:
                    iso2 = record.get("country_iso2")
                    if iso2 and iso2 not in seen:
                        seen.add(iso2)
                        unique_ccyb.append(record)
                self.client.table("latest_ccyb_snapshot").upsert(
                    unique_ccyb,
                    on_conflict="country_iso2"
                ).execute()
                results["ccyb_snapshot"] = len(unique_ccyb)
            
            if snapshots["syrb"]:
                # Remove duplicates
                seen = set()
                unique_syrb = []
                for record in snapshots["syrb"]:
                    iso2 = record.get("country_iso2")
                    if iso2 and iso2 not in seen:
                        seen.add(iso2)
                        unique_syrb.append(record)
                self.client.table("latest_syrb_snapshot").upsert(
                    unique_syrb,
                    on_conflict="country_iso2"
                ).execute()
                results["syrb_snapshot"] = len(unique_syrb)
            
            if snapshots["osii"]:
                # Remove duplicates
                seen = set()
                unique_osii = []
                for record in snapshots["osii"]:
                    iso2 = record.get("country_iso2")
                    if iso2 and iso2 not in seen:
                        seen.add(iso2)
                        unique_osii.append(record)
                self.client.table("latest_osii_snapshot").upsert(
                    unique_osii,
                    on_conflict="country_iso2"
                ).execute()
                results["osii_snapshot"] = len(unique_osii)
            
            # 9. Trends
            logger.info("   -> Migrating trends...")
            if trends["ccyb"]:
                # Remove duplicates based on date
                seen = set()
                unique_ccyb_trends = []
                for record in trends["ccyb"]:
                    date_key = record.get("date")
                    if date_key and date_key not in seen:
                        seen.add(date_key)
                        unique_ccyb_trends.append(record)
                self.client.table("ccyb_diffusion_trend").upsert(
                    unique_ccyb_trends,
                    on_conflict="date"
                ).execute()
                results["ccyb_trend"] = len(unique_ccyb_trends)
            
            if trends["syrb"]:
                # Remove duplicates based on date
                seen = set()
                unique_syrb_trends = []
                for record in trends["syrb"]:
                    date_key = record.get("date")
                    if date_key and date_key not in seen:
                        seen.add(date_key)
                        unique_syrb_trends.append(record)
                self.client.table("syrb_trend").upsert(
                    unique_syrb_trends,
                    on_conflict="date"
                ).execute()
                results["syrb_trend"] = len(unique_syrb_trends)
            
            if trends["bbm"]:
                # Remove duplicates based on date
                seen = set()
                unique_bbm_trends = []
                for record in trends["bbm"]:
                    date_key = record.get("date")
                    if date_key and date_key not in seen:
                        seen.add(date_key)
                        unique_bbm_trends.append(record)
                self.client.table("bbm_diffusion_trend").upsert(
                    unique_bbm_trends,
                    on_conflict="date"
                ).execute()
                results["bbm_trend"] = len(unique_bbm_trends)
            
            logger.info("\n" + "=" * 60)
            logger.info("✅ Migration completed successfully!")
            logger.info("=" * 60)
            logger.info(f"Migrated records: {results}")
            
            results["status"] = "success"
            return results
            
        except Exception as e:
            logger.error(f"\n❌ Migration failed: {e}")
            import traceback
            logger.error(traceback.format_exc())
            results["status"] = "error"
            results["error"] = str(e)
            raise
    
    def migrate_incremental(
        self,
        data_dir: Optional[Path] = None,
        table_name: str = "ccyb_decisions",
    ) -> Dict[str, Any]:
        """
        Migrate only new/updated records (incremental update).
        
        Note: This is a simplified version. Full implementation would require
        tracking last migration timestamp or comparing records.
        
        Args:
            data_dir: Directory containing parquet files
            table_name: Table to update incrementally
            
        Returns:
            Dictionary with migration results
        """
        # TODO: Implement incremental migration logic
        logger.warning("Incremental migration not yet implemented. Use migrate_all() instead.")
        return {"status": "not_implemented"}


if __name__ == "__main__":
    # Example usage
    import sys
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    
    try:
        migrator = SupabaseMigrator()
        
        # Dry run first
        print("\n=== DRY RUN ===")
        results = migrator.migrate_all(validate=True, dry_run=True)
        print(f"Dry run results: {results}")
        
        # Ask for confirmation
        response = input("\nProceed with actual migration? (yes/no): ")
        if response.lower() == "yes":
            print("\n=== ACTUAL MIGRATION ===")
            results = migrator.migrate_all(validate=True, dry_run=False)
            print(f"Migration results: {results}")
        else:
            print("Migration cancelled.")
            
    except Exception as e:
        logger.error(f"Migration failed: {e}")
        sys.exit(1)
